### PR TITLE
Updated to Python 3 and removed NodeBox requirement

### PR DESCRIPTION
**Pull request by TheZoc**
- Updated code to Python 3 with pep8 formatting
- Replaced NodeBox draw calls with pillow

### CODE REVIEW

**Comment by llimllib** [comment]
okay, holy cow I love this. Thank you.

- I haven't looked at this code in a decade, so this is going to take me a minute to review!
- But I want to reiterate: I love it and you're a hero

**Comment by llimllib** [comment]
I have some things I'd like to add/change, but considering that this code is currently basically non-runnable this PR is a strict improvement and I'm going to merge it.

So many thanks!

**Comment by TheZoc** [comment]
@llimllib Hey! Thank you for going through this so fast! 🙂 
I tried to leave as much as possible of the original code (with the exception of the constants, as they were throwing me off - sorry!), so you wouldn't come to a complete alien environment.

Glad to be of help! And thank you for writing the article and code!

**Comment by llimllib** [comment]
yeah it's old code that I never intended to maintain, it was all just hackery for the article. Of course that's the code that ends up lasting a decade!

**Pull request merged**
